using System;
using System.Threading;
using Org.W3C;
using Org.W3C.DOM;
using Net.Bindows;

namespace n4w.ExampleProject
{
	public class MainClass
	{
		public string mensajito;
		public Element button;
		public BiTextField t;
		public BiWindow w;

		public MainClass()
		{
			this.mensajito = "Con un sleep me retraze";
			var biscript = Window.Document.CreateElement("script");
			biscript.SetAttribute("src","/bindows/html/js/application.js");
			biscript.SetAttribute("type","application/javascript");
			Window.Document.Head.AppendChild(biscript);

			var bistyle = Window.Document.CreateElement("link");
			bistyle.SetAttribute("rel","StyleSheet");
			bistyle.SetAttribute("type","text/css");
			bistyle.SetAttribute("href","/bindows/html/css/bimain.css");
			Window.Document.Head.AppendChild(bistyle);

			biscript.AddEventListener("load", this.BindowsLoaded,false);
		}


		public static void Main ()
		{
			new MainClass();
		}

		public void BindowsLoaded (object param)
		{
			Application.Start("/bindows/html", "BindowsApp.xml");

			button = Window.Document.CreateElement("button");

			button.AppendChild(Window.Document.CreateTextNode("Clickeame"));

			button.AddEventListener("click", CuandoClickee, false);

			Window.Document.Body.AppendChild(button);

			Thread.Sleep(1000);

			Window.Alert(this.mensajito);


		}

		public void CuandoClickee(object param) 
		{
			Window.Document.Body.RemoveChild(this.button);
			var xhr = new XMLHttpRequest();
			xhr.Open("GET", "test.txt",false, null, null);
			xhr.Send(null);

			t = new BiTextField();

			var b = new BiButton();
			b.HTML = "<b>Estoy en negrita</b>";
			b.AddEventListener(new BiEventListener("click", CuandoClickeeElBotonDeBindows));
			b.Left = 120;

			w = new BiWindow();
			w.ContentPane.Add(b);
			w.ContentPane.Add(t);
			w.ContentPane.BackColor = "red";
			w.Caption = "Escribime pescado";
			w.Icon = BiImage.FromUri("/bindows/html/themes/Default/images/default.16.gif");

			Application.Window.Add(w);

			Window.Alert(xhr.ResponseText);
		}

		public void CuandoClickeeElBotonDeBindows (object args)
		{
		
			if (t.Text == "pescado") {
				Window.Alert ("Bien chabon, sos mas inteligente que un mono");
				Window.SetTimeout(this.CuandoTermineElTimeout, 1000);
				w.Enabled = false;
			} else {
				Window.Alert ("Dale escribi pescado man!!!");
			}
		}

		public void CuandoTermineElTimeout (object a)
		{
			w.Close();
			Window.Alert("Me cerre con el timeout nativo");


			//n4w.GtkProject.MainClass.Main2(new string[] {});

		}

	}




}
/*
//TODO ESTO TIENE UN PROGRAMA GTK

public class VentanaGtk : Gtk.Window
{
	public void Build()
	{
		this.Name = "MainWindow";
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		//this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}

	public VentanaGtk (): base (Gtk.WindowType.Toplevel)
	{
		Build ();
	}
	
	/*protected void OnDeleteEvent (object sender, DeleteEventArgs a)
	{
		Application.Quit ();
		a.RetVal = true;
	}
}


// This file has been generated by the GUI designer. Do not modify.
namespace Stetic
{
	internal class Gui
	{
		private static bool initialized;
		
		internal static void Initialize (Gtk.Widget iconRenderer)
		{
			if ((Stetic.Gui.initialized == false)) {
				Stetic.Gui.initialized = true;
			}
		}
	}
	
	internal class ActionGroups
	{

		public static Gtk.ActionGroup GetActionGroup (System.Type type)
		{
			return null;
		}
		
		public static Gtk.ActionGroup GetActionGroup (string name)
		{
			return null;
		}
	}
}

namespace n4w.GtkProject
{
	class MainClass
	{
		public static void Main2 (string[] args)
		{
			Gtk.Application.Init ();
			VentanaGtk win = new VentanaGtk ();
			win.Show ();
			Gtk.Application.Run ();
		}
	}
}
*/